[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    adafruit/Adafruit NeoPixel

; Generic ESP32-S3 module with 16 MB QSPI flash and 8 MB OPI PSRAM.
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
monitor_port = COM11
monitor_filters = esp32_exception_decoder
upload_port = COM11
upload_speed = 921600
